package com.supertalk.app.util

object NavDestinations {
    const val SPLASH_SCREEN = "SPLASH_SCREEN"
    const val BASIC_INDRO_SLIDER_SCREEN = "BASIC_INDRO_SLIDER_SCREEN"
    const val LOGIN_SCREEN = "LOGIN_SCREEN"
    const val PRIVACY_SCREEN = "PRIVACY_SCREEN"
    const val TERMS_AND_CONDITIONS_SCREEN = "TERMS_AND_CONDITIONS_SCREEN"
    const val REGISTRATION_OTP_SCREEN = "REGISTRATION_OTP_SCREEN"
    const val HOME_SCREEN = "HOME_SCREEN"
    const val SPORTS_SELECTION_SCREEN = "SPORTS_SELECTION_SCREEN"
    const val LOCATION_SELECTION_SCREEN = "LOCATION_SELECTION_SCREEN"
    const val ACCOUNT_CREATION_SUCCESS_SCREEN = "ACCOUNT_CREATION_SUCCESS_SCREEN"
    const val ROOM_CREATION_SCREEN = "ROOM_CREATION_SCREEN"
    const val ROOM_CREATED_SCREEN = "ROOM_CREATED_SCREEN"
    const val USER_KICK_OUT_SCREEN = "USER_KICK_OUT_SCREEN"
    const val NEWS_DETAILS_SCREEN = "NEWS_DETAILS_SCREEN"
    const val COIN_CARD_BOTTOM_SHEET_SCREEN = "COIN_CARD_BOTTOM_SHEET_SCREEN"
    const val CARD_DETAILS_ENTER_SCREEN = "CARD_DETAILS_ENTER_SCREEN"
    const val SELECT_CARD_SCREEN = "SELECT_CARD_SCREEN"
    const val GROUND_HOME_SCREEN = "GROUND_HOME_SCREEN"
}