package com.supertalk.app.util

object NavDestinations {
    const val SPLASH_SCREEN = "SPLASH_SCREEN"
    const val BASIC_INDRO_SLIDER_SCREEN = "BASIC_INDRO_SLIDER_SCREEN"
    const val LOGIN_SCREEN = "LOGIN_SCREEN"
    const val PRIVACY_SCREEN = "PRIVACY_SCREEN"
    const val TERMS_AND_CONDITIONS_SCREEN = "TERMS_AND_CONDITIONS_SCREEN"
    const val REGISTRATION_OTP_SCREEN = "REGISTRATION_OTP_SCREEN"
    const val SPORTS_SELECTION_SCREEN = "SPORTS_SELECTION_SCREEN"
}