package com.supertalk.app.utils.callbacks
import android.view.View


interface OnItemClickListener {
    fun onItemClick(v: View, obj: Any)
    fun onClick(obj: Any, actionToPerform: OnItemClickActions){}
    fun onClick(actionToPerform: OnItemClickActions){}
    fun onCheckChange(v: View, obj: Any,value:Boolean){}


    enum class OnItemClickActions{
        GO_TO_MOBILE_NUMBER_SCREEN,
        GO_TO_MOBILE_OTP_SCREEN,
        GO_TO_USER_TYPES_SCREEN,
        GO_TO_TEACHER_REG_SCREEN,
        GO_TO_CREATE_CLASS_ROOM,
        GO_TO_CLASS_ROOM_TIMING,
        GO_TO_DASH_BOARD_SCREEN,
        GO_TO_MANAGE_CLASS_SCREEN,
        GO_TO_DRAWER_SCREEN,
        GO_TO_CLASS_DETAILS_SCREEN,
        GO_TO_MENU_SCREEN,
        GO_TO_ADD_OR_EDIT_SCREEN,
        GO_TO_ADD_BANK_DETAILS_SCREEN,
        DRAWER_CANCEL_CLICK,
        GO_TO_STUDENT_REG_SCREEN,
        GO_TO_STUDENT_ENROLLMENT_SCREEN,
        GO_TO_CLASS_ENROLLMENT_SCREEN,
        GO_TO_CLASS_APPROVAL_SCREEN,
        GO_TO_ENROLLED_STUDENTS_SCREEN,
        GO_TO_DASHBOARD_STUDENT_SCREEN,
        GO_TO_LIVE_CLASS_SCREEN,
        APPROVE_ALL_CLICK,
        INFO_CLICK,
        DRAFT_CLICK,
        PUBLISH_CLICK,
        SET_UP_FEE_SCREEN,
        CANCEL_CLICK,
        MAKE_PAYMENT_CLICK,
        TERMS_AND_CONDITION,
        HOME_WORK_CREATE,
        GO_TO_ASSIGN_HOMEWORK,
        GO_TO_UPLOAD_HOMEWORK_SCREEN,
        CAMERA_UPLOAD,
        GALLERY_UPLOAD,
        GO_TO_PREVIEW_SCREEN,
        GO_TO_HOMEWORK_SUBMISSION_DETAILS_SCREEN,
        GO_TO_HOMEWORK_EVALUATION_SCREEN,
        GO_TO_ASSIGNED_HOMEWORK_LIST_SCREEN,
        GO_TO_STUDENT_UPLOAD_HOMEWORK,
        GO_TO_HOMEWORK_COMPLETE_SCREEN,
        GO_TO_HOMEWORK_RESULT_SCREEN,
        GO_TO_ADD_STUDY_MATERIAL,
        GO_TO_NEW_STUDY_MATERIAL,
        GO_TO_UPLOAD_STUDY_MATERIAL,
        UPLOAD_STUDY_MATERIAL,
        CREATE_FOR_UPLOAD_STUDY_MATERIAL,
        GO_TO_CLASS_RECORDINGS_SCREEN,
        GO_TO_CREATE_NEW_ASSIGNMENT,
        GO_TO_CREATE_ASSIGNMENT,
        GO_TO_ASSIGNED_ASSIGNMENT_LIST_SCREEN,
        GO_TO_STUDENT_CLASS_RECORDINGS_SCREEN,
        OPEN_STUDY_MATERIAL,
        GO_TO_ASSIGNMENT_EVALUATION_SCREEN,
    }
}
